package scaffold

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// State is what Update did — or declined to do — with one file.
type State string

const (
	StateCurrent    State = "current"    // already byte-identical to what this hm writes
	StateUpdated    State = "updated"    // rewritten from an older, unmodified generation
	StateCreated    State = "created"    // wasn't there at all
	StateCustomized State = "customized" // skipped: edited locally, or never stamped
	StateForced     State = "forced"     // customized, but overwritten anyway
)

// Result reports Update's verdict for one file.
type Result struct {
	Path  string      // repo-relative
	State State       // what happened, or why it didn't
	From  string      // hm version that wrote the existing file, "" if unstamped
	To    string      // hm version now stamped on it
	Want  []byte      // what this hm would write — populated when State is StateCustomized
	Mode  os.FileMode // mode the file is written with; lets callers diff without a spurious mode change
}

// Skipped reports whether the file was left alone because it's the
// user's now.
func (r Result) Skipped() bool { return r.State == StateCustomized }

// Update refreshes the tool-owned files in an existing environment repo
// — the ones Homie keeps current across releases, as opposed to the
// seeds (homie.toml, home/, scripts/) that become the user's on day one.
// It is the repeatable half of `hm init`: same templates, same answers,
// but against a repo that already exists.
//
// A file is only rewritten when its provenance stamp proves nobody has
// touched it since Homie wrote it. Anything edited locally — or never
// stamped, which covers every repo scaffolded before stamps existed — is
// reported as StateCustomized with the would-be content in Want, so the
// caller can show a diff and let the user decide. force overwrites those.
//
// Update never creates a repo from nothing; that's still Run's job.
func Update(targetDir string, a Answers, version string, force bool) ([]Result, error) {
	if err := a.fillDefaults(); err != nil {
		return nil, err
	}
	var out []Result
	for _, e := range manifest {
		if !e.toolOwned {
			continue
		}
		res, err := updateOne(targetDir, e, a, version, force)
		if err != nil {
			return nil, err
		}
		out = append(out, res)
	}
	return out, nil
}

func updateOne(targetDir string, e entry, a Answers, version string, force bool) (Result, error) {
	raw, err := fs.ReadFile(content, e.src)
	if err != nil {
		return Result{}, fmt.Errorf("read embedded %s: %w", e.src, err)
	}
	body := raw
	if e.rendered {
		if body, err = render(string(raw), a); err != nil {
			return Result{}, fmt.Errorf("render %s: %w", e.src, err)
		}
	}
	want := stampProvenance(body, version)
	res := Result{Path: e.dst, To: version, Mode: e.mode}

	out := filepath.Join(targetDir, e.dst)
	have, err := os.ReadFile(out)
	switch {
	case os.IsNotExist(err):
		res.State = StateCreated
	case err != nil:
		return Result{}, fmt.Errorf("read %s: %w", out, err)
	default:
		p, stamped := readProvenance(have)
		res.From = p.Version
		switch {
		// Compare on digest, not raw bytes: a file generated by this
		// same version carries an identical stamp, so equal digests
		// mean equal content.
		case stamped && p.Digest == digestOf(want) && p.Digest == digestOf(have):
			res.State = StateCurrent
			return res, nil
		case unchangedSince(have):
			res.State = StateUpdated
		case force:
			res.State = StateForced
		default:
			res.State = StateCustomized
			res.Want = want
			return res, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return Result{}, fmt.Errorf("mkdir %s: %w", filepath.Dir(out), err)
	}
	if err := os.WriteFile(out, want, e.mode); err != nil {
		return Result{}, fmt.Errorf("write %s: %w", out, err)
	}
	return res, nil
}
